services:
  prasankit-api:
    build:
      context: ./app-api
    container_name: prasankit_api
    env_file:
      - .env
    ports:
      - "${API_EXTERNAL_PORT}:8080"
    depends_on:
      prasankit-pgsql:
        condition: service_healthy
      prasankit-redis:
        condition: service_healthy
      prasankit-minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/v1/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prasankit_network

  prasankit-pgsql:
    image: postgres:18-alpine
    container_name: prasankit_pgsql
    environment:
      POSTGRES_USER: ${POSTGRES_PRIMARY_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PRIMARY_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PRIMARY_NAME}
      TZ: ${API_TIMEZONE}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_PRIMARY_USER} -d ${POSTGRES_PRIMARY_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prasankit_network

  prasankit-redis:
    image: redis:8-alpine
    container_name: prasankit_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prasankit_network

  prasankit-minio:
    image: minio/minio:latest
    container_name: prasankit_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prasankit_network

  prasankit-web:
    build:
      context: ./app-web
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: prasankit_web
    ports:
      - "${WEB_EXTERNAL_PORT}:3000"
    depends_on:
      prasankit-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prasankit_network

networks:
  prasankit_network:
    name: prasankit_network
