// Package ids provides application-generated UUIDv7 identifiers.
// IDs are generated by the application (no DB default) per conventions in docs/04-data-model.md §2.1.
package ids

import "github.com/google/uuid"

// New returns a new UUIDv7. The caller is responsible for handling the error
// (crypto/rand failure is fatal in practice but must be surfaced).
func New() (uuid.UUID, error) {
	return uuid.NewV7()
}
